---
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: myResourceGroup
      name: win-vm
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      admin_password: "{{ password }}"
      network_interfaces: nic
      os_type: Windows
      image:
          offer: WindowsServer
          publisher: MicrosoftWindowsServer
          sku: 2019-Datacenter
          version: latest
    no_log: true

 # - name: Create Azure VM
  #  hosts: localhost
  #  connection: local
  #  vars_prompt:
  #    - name: password
  #      prompt: "Enter local administrator password"
    #tasks:
